/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habit {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'emoji' : string,
  'category' : HabitCategory,
}
export type HabitCategory = { 'productivity' : null } |
  { 'mindfulness' : null } |
  { 'wellness' : null } |
  { 'health' : null };
export interface HabitCheckIn { 'date' : string, 'habitId' : bigint }
export interface HabitStatsWithHabit {
  'habit' : Habit,
  'longestStreak' : bigint,
  'totalCheckIns' : bigint,
  'currentStreak' : bigint,
}
export interface HabitStatsWithId {
  'habitId' : bigint,
  'longestStreak' : bigint,
  'totalCheckIns' : bigint,
  'currentStreak' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDefaultHabits' : ActorMethod<[], undefined>,
  'addHabit' : ActorMethod<[Habit], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInHabit' : ActorMethod<[bigint, string], undefined>,
  'checkInHabitForAllDays' : ActorMethod<[bigint, Array<string>], undefined>,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'editHabit' : ActorMethod<[bigint, Habit], undefined>,
  'getAllCheckIns' : ActorMethod<[], Array<HabitCheckIn>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckInsByHabit' : ActorMethod<[bigint], Array<string>>,
  'getCurrentStreaks' : ActorMethod<[], Array<HabitStatsWithId>>,
  'getHabitById' : ActorMethod<[bigint], [] | [Habit]>,
  'getHabitStats' : ActorMethod<[], Array<HabitStatsWithHabit>>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getPopularHabits' : ActorMethod<[], Array<Habit>>,
  'getTrendingHabits' : ActorMethod<[], Array<Habit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];