/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HabitCategory = IDL.Variant({
  'productivity' : IDL.Null,
  'mindfulness' : IDL.Null,
  'wellness' : IDL.Null,
  'health' : IDL.Null,
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
  'category' : HabitCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HabitCheckIn = IDL.Record({
  'date' : IDL.Text,
  'habitId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HabitStatsWithId = IDL.Record({
  'habitId' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'totalCheckIns' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const HabitStatsWithHabit = IDL.Record({
  'habit' : Habit,
  'longestStreak' : IDL.Nat,
  'totalCheckIns' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDefaultHabits' : IDL.Func([], [], []),
  'addHabit' : IDL.Func([Habit], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'checkInHabitForAllDays' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'editHabit' : IDL.Func([IDL.Nat, Habit], [], []),
  'getAllCheckIns' : IDL.Func([], [IDL.Vec(HabitCheckIn)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInsByHabit' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getCurrentStreaks' : IDL.Func([], [IDL.Vec(HabitStatsWithId)], ['query']),
  'getHabitById' : IDL.Func([IDL.Nat], [IDL.Opt(Habit)], ['query']),
  'getHabitStats' : IDL.Func([], [IDL.Vec(HabitStatsWithHabit)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getPopularHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getTrendingHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HabitCategory = IDL.Variant({
    'productivity' : IDL.Null,
    'mindfulness' : IDL.Null,
    'wellness' : IDL.Null,
    'health' : IDL.Null,
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
    'category' : HabitCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HabitCheckIn = IDL.Record({ 'date' : IDL.Text, 'habitId' : IDL.Nat });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HabitStatsWithId = IDL.Record({
    'habitId' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'totalCheckIns' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const HabitStatsWithHabit = IDL.Record({
    'habit' : Habit,
    'longestStreak' : IDL.Nat,
    'totalCheckIns' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDefaultHabits' : IDL.Func([], [], []),
    'addHabit' : IDL.Func([Habit], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'checkInHabitForAllDays' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'editHabit' : IDL.Func([IDL.Nat, Habit], [], []),
    'getAllCheckIns' : IDL.Func([], [IDL.Vec(HabitCheckIn)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInsByHabit' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getCurrentStreaks' : IDL.Func([], [IDL.Vec(HabitStatsWithId)], ['query']),
    'getHabitById' : IDL.Func([IDL.Nat], [IDL.Opt(Habit)], ['query']),
    'getHabitStats' : IDL.Func([], [IDL.Vec(HabitStatsWithHabit)], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getPopularHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getTrendingHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };